name: concert_predictor
channels:
  - conda-forge
dependencies:
  - python=3.9             # Fuerza Python 3.9
  - streamlit=1.45.1       # Instalado desde conda-forge
  - pandas=1.3.5
  - numpy=1.21.6
  - scipy=1.7.3
  - scikit-learn=1.0.2
