name: concert_predictor
channels:
  - conda-forge
dependencies:
  - python=3.9        # fuerza Python 3.9 para compatibilidad con tus pickles
  - scikit-learn=1.0.2
  - numpy=1.21.6
  - scipy=1.7.3
  - pandas=1.3.5
  - pip
  - pip:
    - streamlit==1.45.1
